---
version: '3'
services:
  path_calc_api:
    build: "./path_calc_api"
    command: /bin/sh -c "bundle exec rake db:create db:migrate db:seed &&
      bundle exec rake db:migrate db:seed RAILS_ENV=test && bundle exec rails s -p 3001 -b 0.0.0.0"
    ports:
    - 3001:3001
  routes:
    build: "./routes"
    command: /bin/sh -c "bundle exec rails s -p 3002 -b 0.0.0.0"
    ports:
    - 3002:3002
